version: "3"
name: "squirtle-app"
services:
  postgres:
    image: postgres:16-alpine
    container_name: squirtle_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "10086:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
